# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml
trigger: none
pr:
- dev
- master
pool:
  vmImage: ubuntu-latest
steps:
- task: DownloadSecureFile@1
  name: keysEnv
  inputs:
    secureFile: 'keys.env'
    retryCount: '2'

- script: 
    cp $(keysEnv.secureFilePath) ./keys.env

    
- task: FlutterInstall@0
- task: FlutterBuild@0
  inputs:
    target: 'apk'
    debugMode: true
    projectDirectory: '.'
- task: FlutterTest@0
  inputs:
    projectDirectory: '.'
