# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: ubuntu-latest


stages:
  - stage: build
    jobs:
    - job: build
      steps:
        - task: DownloadSecureFile@1
          name: keysEnv
          inputs:
            secureFile: 'keys.env'
            retryCount: '2'
        - script: cp $(keysEnv.secureFilePath) ./keys.env
        - script: rm ./.env
        - script: echo $(pumec-server-env) > ./.env
        - task: FlutterInstall@0
        - task: FlutterBuild@0
          inputs:
            target: 'apk'
            debugMode: true

        - task: PublishBuildArtifacts@1
          inputs:
            PathtoPublish: './build/app/outputs/apk/debug/app-debug.apk'
            ArtifactName: 'pumec-server-apk'
            publishLocation: 'Container'

